package proyecto;

import controller.GestorDeGestores;
import controller.GestorCitas;
import modelo.Cita;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmConsultas extends javax.swing.JFrame {

    private GestorDeGestores gg;
    private GestorCitas gestorCitas;
    private DefaultTableModel modelo;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConsultas.class.getName());

    public FrmConsultas() {
        initComponents();
        setLocationRelativeTo(null); //centra la ventana
    }

    public FrmConsultas(GestorDeGestores gg) {
        this();  //llama al constructor sin parametros
        this.gg = gg;
        this.gestorCitas = gg.getGestorCitas(); // tomo el gestor de citas
        configurarTabla();    // setea columnas y no editable
        cargarTabla();        // llena la tabla con las citas actuales
    }

    private void configurarTabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false; //solo lectura
            }
        };
        modelo.addColumn("Id");           //columnas
        modelo.addColumn("FechaHora");
        modelo.addColumn("PacienteDoc");
        modelo.addColumn("Medico"); //dni
        modelo.addColumn("Consultorio"); //codigo
        modelo.addColumn("Estado");
        modelo.addColumn("Modalidad");
        tblConsultas.setModel(modelo);
    }

    private void limpiarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0); //borra filas una por una
        }
    }

    private void limpiarCampos() {
        txtId.setText("");
        txtFechaHora.setText("");
        txtPacienteDoc.setText("");
        txtMedico.setText("");
        txtConsultorio.setText("");
        cbEstado.setSelectedIndex(0);
        cbModalidad.setSelectedIndex(0);
        txtId.requestFocus();   //limpia inputs, focus id y selected 0
    }

    private void cargarTabla() {
        limpiarTabla();                                   
        Cita[] arr = gestorCitas.getCitas();              
        int cant = gestorCitas.getCantidad();             
        for (int i = 0; i < cant; i++) {
            Cita c = arr[i];                              
            modelo.addRow(new Object[]{
                c.getId(), // id
                c.getFecha(), // fecha/hora
                c.getPaciente().getDocumento(), // doc paciente
                c.getMedico(), // medico dni
                c.getConsultorio(), // consultorio codigo
                c.getEstado(), // estado
                c.getModalidad() // modalidad
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtPacienteDoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        txtMedico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        txtConsultorio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        txtFechaHora = new javax.swing.JTextField();
        cbModalidad = new javax.swing.JComboBox<>();
        txtHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(167, 215, 209));

        jLabel2.setForeground(new java.awt.Color(45, 62, 80));
        jLabel2.setText("Fecha");

        jLabel3.setForeground(new java.awt.Color(45, 62, 80));
        jLabel3.setText("PacienteDoc");

        btnRegistrar.setBackground(new java.awt.Color(158, 191, 218));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(27, 28, 74));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(45, 62, 80));
        jLabel4.setText("Medico");

        btnBuscar.setBackground(new java.awt.Color(158, 191, 218));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(27, 28, 74));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtPacienteDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteDocActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(45, 62, 80));
        jLabel5.setText("Consultorio");

        btnListar.setBackground(new java.awt.Color(158, 191, 218));
        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListar.setForeground(new java.awt.Color(27, 28, 74));
        btnListar.setText("Listar Todos");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        txtMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(45, 62, 80));
        jLabel6.setText("Modalidad");

        btnCerrar.setBackground(new java.awt.Color(247, 196, 196));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(74, 28, 28));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(45, 62, 80));
        jLabel10.setText("Estado");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual" }));

        jLabel1.setForeground(new java.awt.Color(45, 62, 80));
        jLabel1.setText("Id");

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblConsultas);

        cbModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programada", "Confirmada", "En sala", "Atendida" }));

        jLabel7.setForeground(new java.awt.Color(45, 62, 80));
        jLabel7.setText("Hora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 23, Short.MAX_VALUE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtConsultorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(txtPacienteDoc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMedico, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPacienteDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnListar)
                    .addComponent(btnCerrar))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19))
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // 1) Leer datos del formulario
        String id = txtId.getText();
        String fecha = txtFechaHora.getText();
        String hora = txtHora.getText().trim();
        String pacDoc = txtPacienteDoc.getText();
        String medDni = txtMedico.getText();
        String consCodigo = txtConsultorio.getText();
        String modalidad = cbModalidad.getSelectedItem().toString();
        String estado = cbEstado.getSelectedItem().toString();

        // 2) Buscar objetos en los gestores (via gg)
        //    (ajusta los nombres de metodos si tus gestores difieren)
        modelo.Paciente paciente = gg.getGestorPacientes().buscarPorDocumento(pacDoc);
        if (paciente == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Paciente no encontrado");
            return;
        }

        modelo.Empleado medico = gg.getGestorEmpleados().buscarPorDni(medDni);
        if (medico == null || !"MEDICO".equals(medico.getRol())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Medico no encontrado o rol invalido");
            return;
        }

        modelo.Consultorio consultorio = gg.getGestorConsultorios().buscarPorCodigo(consCodigo);
        if (consultorio == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Consultorio no encontrado");
            return;
        }

        // 4) Validar que no exista una cita con el mismo id
        if (gestorCitas.buscarPorId(id) != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe una cita con ese Id");
            return;
        }

        // 5) Crear la cita y registrar
        Cita cita = new Cita(
                id,
                paciente,
                medico,
                consultorio,
                fecha,
                hora, // <-- faltaba este
                modalidad,
                estado
        );

        boolean ok = gestorCitas.registrarCita(cita);
        if (!ok) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar (sin espacio o duplicado)");
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Cita registrada");
        // Si tienes estos metodos en tu form:
        limpiarCampos();
        cargarTabla();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String id = txtId.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese Id");
            return;
        }
        Cita c = gestorCitas.buscarPorId(id);   // tu metodo
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Cita no encontrada");
        } else {
            txtFechaHora.setText(c.getFecha());
            txtPacienteDoc.setText(c.getPaciente().getDocumento());
            txtMedico.setText(c.getMedico().getDni());
            txtConsultorio.setText(c.getConsultorio().getCodigo());
            cbEstado.setSelectedItem(c.getEstado());
            cbModalidad.setSelectedItem(c.getModalidad());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        //cierra esta ventana
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtPacienteDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteDocActionPerformed

    private void txtMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmConsultas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbModalidad;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JTextField txtConsultorio;
    private javax.swing.JTextField txtFechaHora;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtPacienteDoc;
    // End of variables declaration//GEN-END:variables
}
