package proyecto;

import controller.GestorDeGestores;
import controller.GestorReportes;
import controller.GestorFacturacion;
import modelo.Factura;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

// ------------TABLAS NO EDITABLES---------------
public class FrmReportes extends javax.swing.JFrame {

    private GestorDeGestores gg;
    private GestorReportes gestorReportes;
    private DefaultTableModel modelo;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());

    public FrmReportes() {
        initComponents();
        setLocationRelativeTo(null);
        configurarTablaVacia();
    }

    public FrmReportes(GestorDeGestores gg) {
        this();
        this.gg = gg;
        this.gestorReportes = gg.getGestorReportes();
    }

    private void configurarTablaVacia() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tblReportes.setModel(modelo);
        lblTitulo.setText("Reportes");
        lblResumen.setText(" ");
    }

    private void cargarEnTabla(String[] columnas, Object[][] datos) {
        configurarTablaVacia();
        for (String c : columnas) {
            modelo.addColumn(c);
        }
        if (datos != null) {
            for (Object[] fila : datos) {
                modelo.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContactoEmergencia = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPacientes = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblResumen = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();

        jScrollPane2.setViewportView(jEditorPane1);

        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar Todos");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(45, 62, 80));
        jLabel6.setText("Telefono");

        btnCerrar1.setText("Cerrar");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(45, 62, 80));
        jLabel7.setText("Email");

        jLabel8.setForeground(new java.awt.Color(45, 62, 80));
        jLabel8.setText("Contacto Emergencia");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMBRE", "MUJER" }));

        jLabel10.setForeground(new java.awt.Color(45, 62, 80));
        jLabel10.setText("Sexo");

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblPacientes);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(167, 215, 209));

        btnPacientes.setBackground(new java.awt.Color(158, 191, 218));
        btnPacientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPacientes.setForeground(new java.awt.Color(27, 28, 74));
        btnPacientes.setText("Pacientes");
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });

        btnEmpleados.setBackground(new java.awt.Color(158, 191, 218));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(27, 28, 74));
        btnEmpleados.setText("Empleados\n");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnIngresos.setBackground(new java.awt.Color(158, 191, 218));
        btnIngresos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIngresos.setForeground(new java.awt.Color(27, 28, 74));
        btnIngresos.setText("Ingresos\n");
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(247, 196, 196));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(74, 28, 28));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblTitulo.setForeground(new java.awt.Color(45, 62, 80));
        lblTitulo.setText("Titulo");

        lblResumen.setForeground(new java.awt.Color(45, 62, 80));
        lblResumen.setText("Resumen");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jTable2);

        jScrollPane6.setViewportView(jScrollPane7);

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblReportes);

        jScrollPane6.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIngresos)
                        .addGap(11, 11, 11)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(20, 20, 20)
                .addComponent(lblResumen)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPacientes)
                    .addComponent(btnEmpleados)
                    .addComponent(btnIngresos)
                    .addComponent(btnCerrar))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19))
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        //cierra esta ventana
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        if (gg == null) {
            JOptionPane.showMessageDialog(this, "No hay referencia a GestorDeGestores");
            return;
        }
        GestorFacturacion gf = gg.getGestorFacturacion();
        if (gf == null) {
            JOptionPane.showMessageDialog(this, "No hay gestor de facturacion");
            return;
        }

        // columnas
        String[] cols = {"Id", "PacienteDoc", "Consulta", "Servicios", "Total", "Pago"};
        configurarTablaVacia();
        for (String c : cols) {
            modelo.addColumn(c);
        }

        Factura[] arr = gf.getFacturas();
        int n = gf.getCantidad();

        double sumaConsulta = 0.0;
        double sumaServicios = 0.0;
        double sumaTotal = 0.0;

        for (int i = 0; i < n; i++) {
            Factura f = arr[i];
            Object[] fila = new Object[]{
                f.getId(),
                f.getPaciente().getDocumento(), // o nombres si prefieres
                f.getMontoConsulta(),
                f.getMontoServicios(),
                f.getTotal(),
                f.getMetodoPago()
            };
            modelo.addRow(fila);

            // acumular
            sumaConsulta = sumaConsulta + f.getMontoConsulta();
            sumaServicios = sumaServicios + f.getMontoServicios();
            sumaTotal = sumaTotal + f.getTotal();
        }

        // fila en blanco + totales
        modelo.addRow(new Object[]{"", "", "", "", "", ""});
        modelo.addRow(new Object[]{"Totales", "", sumaConsulta, sumaServicios, sumaTotal, ""});

        lblTitulo.setText("Ingresos");
        lblResumen.setText("Registros: " + n + "  |  Total ingresos: " + sumaTotal);
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        if (gestorReportes == null) {
            JOptionPane.showMessageDialog(this, "No hay referencia a GestorReportes");
            return;
        }
        String[] cols = gestorReportes.columnasEmpleados();
        Object[][] data = gestorReportes.datosEmpleados();
        cargarEnTabla(cols, data);
        lblTitulo.setText("Empleados");

        // resumen por rol
        int[] conteo = gestorReportes.conteoEmpleadosPorRol();
        String[] roles = gestorReportes.rolesBase();

        // fila en blanco + encabezado de resumen (simple)
        modelo.addRow(new Object[]{"", "", "", "", ""});
        modelo.addRow(new Object[]{"Resumen por rol", "", "", "", ""});
        for (int i = 0; i < roles.length; i++) {
            modelo.addRow(new Object[]{roles[i], conteo[i], "", "", ""});
        }

        lblResumen.setText("Total empleados: " + data.length);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        if (gestorReportes == null) {
            JOptionPane.showMessageDialog(this, "No hay referencia a GestorReportes");
            return;
        }
        String[] cols = gestorReportes.columnasPacientes();
        Object[][] data = gestorReportes.datosPacientes();
        cargarEnTabla(cols, data);
        lblTitulo.setText("Pacientes");
        lblResumen.setText("Total pacientes: " + data.length);
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        //cierra esta ventana
        this.dispose();
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTable tblReportes;
    private javax.swing.JTextField txtContactoEmergencia;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
